package com.shahboun.routeroptimizer;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import org.json.JSONArray;
import java.io.*;
import java.net.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.regex.*;

public class MainActivity extends Activity {
  final Handler h=new Handler(Looper.getMainLooper());
  final Map<String,TextView> views=new HashMap<>();
  final Map<String,String> cache=new HashMap<>();
  SharedPreferences prefs;
  LinearLayout root,body,nav,routerBar; ScrollView scroll; WebView web; TextView status;
  String baseUrl="http://192.168.8.1", password="admin", vendor="راوتر متصل", driver="Pending";
  boolean authenticated=false,phoneMode=false,probing=false,live=false,huawei=false;
  long prevDl=-1,prevUl=-1,prevTs=0;
  final int BG=Color.rgb(3,10,18),SURFACE=Color.rgb(8,22,34),CARD=Color.rgb(12,31,46),CARD2=Color.rgb(17,43,61),EDGE=Color.rgb(35,68,88),TEXT=Color.rgb(243,248,252),MUTED=Color.rgb(184,204,220),ACCENT=Color.rgb(77,198,220);
  final Typeface REG=Typeface.create("sans-serif",Typeface.NORMAL),MED=Typeface.create("sans-serif-medium",Typeface.NORMAL);
  final String[][] BANDS={{"تلقائي / الأصل","20800800D5","00"},{"B1","1","03"},{"B3","4","03"},{"B5","10","03"},{"B7","40","03"},{"B8","80","03"},{"B20","80000","03"},{"B32","80000000","03"},{"B38","2000000000","03"},{"B3+B7","44","03"},{"B7+B8","C0","03"},{"B7+B20","80040","03"},{"B8+B20","80080","03"},{"B3+B7+B20","80044","03"},{"B7+B8+B20","800C0","03"},{"B3+B7+B8+B20","800C4","03"},{"كل LTE Bands","7FFFFFFFFFFFFFFF","03"}};

  @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("shahboun_router",MODE_PRIVATE);baseUrl=prefs.getString("baseUrl",baseUrl);password=prefs.getString("routerPassword","admin");getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);build();h.postDelayed(this::detectRouter,500);}
  int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
  TextView tv(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(REG);t.setPadding(dp(10),dp(8),dp(10),dp(8));return t;}
  GradientDrawable shape(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),EDGE);return g;}
  void build(){
    root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
    if(Build.VERSION.SDK_INT>=21)root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});
    LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(16),dp(12),dp(12),dp(10));
    LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);TextView title=tv("Shahboun Router",24,TEXT);title.setTypeface(MED);title.setPadding(0,0,0,0);names.addView(title);TextView sub=tv("Smart Router Control  •  v0.11.2",11,MUTED);sub.setPadding(0,dp(2),0,0);names.addView(sub);head.addView(names,new LinearLayout.LayoutParams(0,-2,1));TextView scan=button("إعادة كشف",x->detectRouter());head.addView(scan,new LinearLayout.LayoutParams(dp(106),dp(44)));root.addView(head);
    status=tv("جاهز للاتصال",12,TEXT);status.setGravity(Gravity.CENTER);status.setBackgroundColor(SURFACE);status.setMinHeight(dp(44));root.addView(status);
    routerBar=new LinearLayout(this);routerBar.setPadding(dp(6),dp(5),dp(6),dp(5));routerBar.setVisibility(View.GONE);small("رجوع",x->hideRouter());small("الرئيسية",x->web.loadUrl(baseUrl+"/"));small("تحديث",x->web.reload());small("ملاءمة",x->fitRouter());root.addView(routerBar);
    scroll=new ScrollView(this);scroll.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(8),dp(14),dp(22));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
    web=new WebView(this);WebSettings ws=web.getSettings();ws.setJavaScriptEnabled(true);ws.setDomStorageEnabled(true);ws.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);ws.setUseWideViewPort(true);ws.setLoadWithOverviewMode(true);ws.setBuiltInZoomControls(true);ws.setDisplayZoomControls(false);web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView w,String u){if(u!=null&&u.startsWith(baseUrl)&&!phoneMode)h.postDelayed(()->autoLogin(),300);}});web.addJavascriptInterface(new JsBridge(),"Shahboun");web.setVisibility(View.GONE);root.addView(web,new LinearLayout.LayoutParams(-1,0));
    nav=new LinearLayout(this);nav.setPadding(dp(6),dp(4),dp(6),dp(6));nav.setBackgroundColor(Color.rgb(4,16,25));navItem("الرئيسية",0);navItem("الشبكة",1);navItem("الأجهزة",2);navItem("الأدوات",3);navItem("الإعدادات",4);root.addView(nav,new LinearLayout.LayoutParams(-1,dp(64)));setContentView(root);showPage(0);
  }
  TextView button(String s,View.OnClickListener l){TextView b=tv(s,12,TEXT);b.setGravity(Gravity.CENTER);b.setTypeface(MED);b.setBackground(shape(CARD2,16));b.setOnClickListener(l);return b;}
  void small(String s,View.OnClickListener l){TextView b=button(s,l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(40),1);p.setMargins(2,0,2,0);routerBar.addView(b,p);}
  void navItem(String s,int p){TextView b=tv(s,10,MUTED);b.setGravity(Gravity.CENTER);b.setOnClickListener(x->showPage(p));nav.addView(b,new LinearLayout.LayoutParams(0,-1,1));}
  void clear(){body.removeAllViews();views.clear();}
  void section(String a,String b){TextView x=tv(a,18,TEXT);x.setTypeface(MED);x.setPadding(2,dp(14),2,0);body.addView(x);TextView y=tv(b,11,MUTED);y.setPadding(2,0,2,dp(7));body.addView(y);}
  void rows(String[][] rs){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(10),dp(14),dp(10));c.setBackground(shape(CARD,20));for(String[] r:rs){LinearLayout ln=new LinearLayout(this);ln.setGravity(Gravity.CENTER_VERTICAL);TextView l=tv(r[0],12,MUTED);ln.addView(l,new LinearLayout.LayoutParams(0,-2,1));TextView z=tv(cache.getOrDefault(r[1],"—"),12,TEXT);z.setGravity(Gravity.END);z.setTypeface(MED);views.put(r[1],z);ln.addView(z,new LinearLayout.LayoutParams(0,-2,1.1f));c.addView(ln);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(9));body.addView(c,p);}
  void grid(String[] labels,View.OnClickListener[] ls){for(int i=0;i<labels.length;i+=2){LinearLayout r=new LinearLayout(this);TextView a=button(labels[i],ls[i]);r.addView(a,new LinearLayout.LayoutParams(0,dp(62),1));Space sp=new Space(this);r.addView(sp,new LinearLayout.LayoutParams(dp(8),1));if(i+1<labels.length)r.addView(button(labels[i+1],ls[i+1]),new LinearLayout.LayoutParams(0,dp(62),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(4),0,dp(4));body.addView(r,p);}}
  void setV(String k,String s){if(s==null||s.trim().isEmpty())return;cache.put(k,s.trim());TextView t=views.get(k);if(t!=null)t.setText(s.trim());}
  void showPage(int p){live=false;clear();if(p==0)home();else if(p==1)network();else if(p==2)devices();else if(p==3)tools();else settings();}
  void home(){section("الحالة المباشرة","قراءة الراوتر كل ثانيتين بعد الدخول");rows(new String[][]{{"الراوتر","vendor"},{"الموديل","model"},{"الشبكة","networkType"},{"الجودة","quality"},{"Band","band"},{"SINR","sinr"},{"RSRP","rsrp"},{"RSRQ","rsrq"},{"Cell ID","cell"},{"PCI","pci"},{"EARFCN","earfcn"},{"WAN IP","wanIp"}});section("الأداء اللحظي","ترافيك مباشر + آخر اختبار سرعة");rows(new String[][]{{"تنزيل لحظي","liveDl"},{"رفع لحظي","liveUl"},{"إجمالي تنزيل","totalDl"},{"إجمالي رفع","totalUl"},{"مدة الاتصال","uptime"},{"آخر Download Test","dl"},{"آخر Upload Test","ul"},{"Ping","ping"},{"Jitter","jitter"},{"Packet Loss","loss"},{"أفضل تردد","bestBand"}});grid(new String[]{"اختبار سرعة كامل","تحسين ذكي","تثبيت أفضل تردد","الترددات","الأجهزة و QoS","SIM Unlock Center","API / Firmware Explorer","استرجاع آمن"},new View.OnClickListener[]{x->speedTest(),x->smartOptimize(),x->pinBest(),x->bands(),x->deviceControl(),x->simCenter(),x->capabilities(),x->safeRestore()});live=true;liveTick();}
  void network(){section("الشبكة الخلوية / WAN","تحكم مباشر حسب API الراوتر");rows(new String[][]{{"الشركة","vendor"},{"Driver","driver"},{"NetworkMode","netMode"},{"LTEBand Mask","lteMask"},{"المشغل","operator"},{"Cell ID","cell"},{"PCI","pci"},{"EARFCN","earfcn"}});grid(new String[]{"الترددات والدمج","APN","SMS","إعادة تشغيل","SIM Unlock Center","واجهة الراوتر"},new View.OnClickListener[]{x->bands(),x->apn(),x->sms(),x->restart(),x->simCenter(),x->showRouter()});refreshAll();}
  void devices(){section("أجهزة الشبكة","الإدارة حسب إمكانيات الراوتر");rows(new String[][]{{"عدد الأجهزة","hosts"},{"Wi-Fi Users","wifiUsers"},{"Gateway","gateway"}});grid(new String[]{"عرض الأجهزة","تحديد السرعة QoS","إدارة Wi-Fi","تحديث"},new View.OnClickListener[]{x->loadHosts(),x->deviceControl(),x->showRouter(),x->refreshAll()});refreshAll();}
  void tools(){section("الأدوات الذكية","قياس وتشخيص وسجل النتائج");rows(new String[][]{{"Download","dl"},{"Upload","ul"},{"Ping","ping"},{"Jitter","jitter"},{"Packet Loss","loss"},{"أفضل تردد","bestBand"}});grid(new String[]{"اختبار سرعة كامل","تشخيص ذكي","Auto Optimizer","سجل السرعة","أفضل تردد","استرجاع آمن"},new View.OnClickListener[]{x->speedTest(),x->diagnose(),x->smartOptimize(),x->history(),x->pinBest(),x->safeRestore()});}
  void settings(){section("الإعدادات","Shahboun Router v0.11.2 — Deep Driver + Universal Core");rows(new String[][]{{"عنوان الراوتر","gateway"},{"الشركة","vendor"},{"الموديل","model"},{"Firmware","firmware"},{"WebUI","webui"},{"Driver","driver"},{"أفضل تردد","bestBand"}});grid(new String[]{"إعادة كشف الراوتر","تسجيل الدخول","API / Firmware Explorer","SIM Unlock Center","واجهة الإدارة","استرجاع آمن","حول التطبيق"},new View.OnClickListener[]{x->detectRouter(),x->loginDialog(),x->capabilities(),x->simCenter(),x->showRouter(),x->safeRestore(),x->about()});}
  void liveTick(){if(!live)return;if(authenticated||phoneMode){refreshAll();}h.postDelayed(this::liveTick,2000);}

  void detectRouter(){if(probing)return;probing=true;status.setText("جارٍ اكتشاف الراوتر...");new Thread(()->{LinkedHashSet<String> ips=new LinkedHashSet<>(Arrays.asList(baseUrl,"http://192.168.8.1","http://192.168.1.1","http://192.168.0.1","http://192.168.100.1","http://10.0.0.1"));String found=null;for(String u:ips){try{String p=get(u+"/",1500);if(p!=null&&!p.isEmpty()){found=u;break;}}catch(Exception ignored){}}String f=found;runOnUiThread(()->{probing=false;if(f==null){status.setText("لم يتم العثور على راوتر");new AlertDialog.Builder(this).setTitle("لا يوجد راوتر").setMessage("اتصل بـ Wi-Fi ثم أعد المحاولة، أو استخدم اختبار السرعة من بيانات الهاتف.").setPositiveButton("بيانات الهاتف",(d,w)->{phoneMode=true;authenticated=true;vendor="بيانات الهاتف";driver="Android Mobile";showPage(0);}).setNegativeButton("إعادة",(d,w)->detectRouter()).show();return;}baseUrl=f;prefs.edit().putString("baseUrl",f).apply();setV("gateway",f);web.loadUrl(f+"/");h.postDelayed(this::loginDialog,350);});}).start();}
  String get(String u,int timeout)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(timeout);c.setReadTimeout(timeout);InputStream in=c.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[4096];int n,total=0;while((n=in.read(b))>0&&total<150000){o.write(b,0,n);total+=n;}in.close();return o.toString("UTF-8");}
  void loginDialog(){if(phoneMode)return;LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(5),dp(20),0);EditText user=new EditText(this);user.setText("admin");user.setEnabled(false);box.addView(user,new LinearLayout.LayoutParams(-1,dp(52)));EditText pass=new EditText(this);pass.setText(password);pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);box.addView(pass,new LinearLayout.LayoutParams(-1,dp(52)));AlertDialog d=new AlertDialog.Builder(this).setTitle("دخول الراوتر").setMessage("اسم المستخدم: admin").setView(box).setPositiveButton("اتصال",null).create();d.setCancelable(false);d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{password=pass.getText().toString().trim();if(password.isEmpty())password="admin";prefs.edit().putString("routerPassword",password).apply();authenticated=false;status.setText("جارٍ تسجيل الدخول...");web.loadUrl(baseUrl+"/");h.postDelayed(()->verify(d),1800);}));d.show();}
  void autoLogin(){if(phoneMode)return;String p=password.replace("\\","\\\\").replace("'","\\'");String js="javascript:(()=>{try{let u=document.querySelector('input[name=username],#username,input[type=text]');let pw=document.querySelector('input[name=password],#password,input[type=password]');if(!pw)return 'noform';if(u)u.value='admin';pw.value='"+p+"';let b=document.querySelector('#login_btn,#loginbutton,button[type=submit],input[type=submit],.login_button,.btn_login');if(b){b.click();return 'clicked'}return 'nobutton'}catch(e){return 'err'}})()";web.evaluateJavascript(js,null);}
  void verify(AlertDialog d){String js="javascript:(async()=>{const g=async u=>{try{return await (await fetch(u,{credentials:'same-origin',cache:'no-store'})).text()}catch(e){return 'NETERR'}};let a=await g('/api/device/information');let b=await g('/api/device/signal');let c=await g('/api/net/net-mode');let e=await g('/api/user/state-login');let s=await g('/api/monitoring/status');return a+'|||'+b+'|||'+c+'|||'+e+'|||'+s})()";web.evaluateJavascript(js,val->{String out=decode(val),low=out.toLowerCase(Locale.US);boolean ok=out.contains("<DeviceName>")||out.contains("<SerialNumber>")||low.contains("<rsrp>")||out.contains("<NetworkMode>")||low.contains("<username>admin</username>")||out.contains("<ConnectionStatus>");boolean denied=low.contains("100003")||low.contains("100002")||low.contains("unauthorized")||low.contains("not login");if(ok){authenticated=true;huawei=true;vendor="Huawei / HiLink";driver="HuaweiHiLink Deep";prefs.edit().putBoolean("huawei",true).apply();d.dismiss();status.setText("تم الدخول • Huawei HiLink Deep Driver");showPage(0);refreshAll();}else if(denied||low.contains("neterr")){Toast.makeText(this,"خطأ في رمز دخول الراوتر",Toast.LENGTH_LONG).show();status.setText("رمز الدخول غير صحيح أو الجلسة غير مفعلة");}else{Toast.makeText(this,"تعذر تأكيد دخول الإدارة",Toast.LENGTH_LONG).show();}});}
  String decode(String v){try{return new JSONArray("["+v+"]").getString(0);}catch(Exception e){return v==null?"":v.replace("\\n","\n").replace("\\\"","\"");}}
  void refreshAll(){if(phoneMode){setV("vendor","هاتف Android");setV("driver","Mobile Data");return;}if(!authenticated)return;setV("vendor",vendor);setV("driver",driver);setV("gateway",baseUrl);String js="javascript:(async()=>{const q=async(u,k)=>{try{let r=await fetch(u,{credentials:'same-origin',cache:'no-store'});let t=await r.text();Shahboun.data(k,t)}catch(e){Shahboun.data(k,'NETERR')}};await Promise.all([q('/api/device/signal','signal'),q('/api/monitoring/status','status'),q('/api/device/information','device'),q('/api/net/net-mode','net'),q('/api/wlan/host-list','hosts'),q('/api/monitoring/traffic-statistics','traffic'),q('/api/net/current-plmn','plmn')])})()";web.evaluateJavascript(js,null);}
  boolean err(String x){if(x==null)return true;String l=x.toLowerCase(Locale.US);return l.contains("<error>")||l.contains("100003")||l.contains("100002")||l.equals("neterr");}
  String tag(String x,String... ns){if(x==null)return "";for(String n:ns){Matcher m=Pattern.compile("<"+Pattern.quote(n)+">(.*?)</"+Pattern.quote(n)+">",Pattern.DOTALL|Pattern.CASE_INSENSITIVE).matcher(x);if(m.find())return m.group(1).trim();}return "";}
  double num(String s){try{return Double.parseDouble(s.replaceAll("[^0-9+\\-.]",""));}catch(Exception e){return 0;}}
  void parseSignal(String x){if(err(x))return;String rsrp=tag(x,"rsrp","Rsrp"),rsrq=tag(x,"rsrq","Rsrq"),sinr=tag(x,"sinr","Sinr"),band=tag(x,"band","Band"),pci=tag(x,"pci","Pci"),cell=tag(x,"cell_id","cellid","CellID"),ear=tag(x,"earfcn","dl_earfcn","EARFCN");if(!band.isEmpty())setV("band",band.toUpperCase().startsWith("B")?band:"B"+band);setV("rsrp",rsrp);setV("rsrq",rsrq);setV("sinr",sinr);setV("pci",pci);setV("cell",cell);setV("earfcn",ear);double si=num(sinr),rp=num(rsrp),rq=num(rsrq);if(!sinr.isEmpty())setV("quality",si>=15&&rp>=-90&&rq>=-10?"ممتاز":si>=8?"جيد":si>=3?"متوسط":"ضعيف / تداخل مرتفع");}
  void parseStatus(String x){if(err(x))return;String nt=tag(x,"CurrentNetworkTypeEx","CurrentNetworkType"),wan=tag(x,"WanIPAddress","WanIPAddr"),u=tag(x,"CurrentWifiUser","CurrentWifiUserNum");setV("networkType",("101".equals(nt)||"19".equals(nt))?"4G LTE":("20".equals(nt)||"1011".equals(nt))?"5G / NR":nt);setV("wanIp",wan);setV("wifiUsers",u);}
  void parseDevice(String x){if(err(x))return;setV("model",tag(x,"DeviceName","Classify","ProductFamily"));setV("firmware",tag(x,"SoftwareVersion"));setV("webui",tag(x,"WebUIVersion"));}
  void parseNet(String x){if(err(x))return;setV("netMode",tag(x,"NetworkMode"));setV("lteMask",tag(x,"LTEBand"));}
  void parseTraffic(String x){if(err(x))return;String cd=tag(x,"CurrentDownloadRate"),cu=tag(x,"CurrentUploadRate"),tds=tag(x,"TotalDownload"),tus=tag(x,"TotalUpload"),dur=tag(x,"CurrentConnectTime","CurrentConnectTimeSecond");long now=System.currentTimeMillis(),td=lng(tds),tu=lng(tus);double dl=-1,ul=-1;if(lng(cd)>0)dl=lng(cd)*8.0/1e6;if(lng(cu)>0)ul=lng(cu)*8.0/1e6;if(prevTs>0&&now>prevTs){double sec=(now-prevTs)/1000.0;if(dl<0&&prevDl>=0&&td>=prevDl)dl=(td-prevDl)*8/sec/1e6;if(ul<0&&prevUl>=0&&tu>=prevUl)ul=(tu-prevUl)*8/sec/1e6;}if(dl>=0)setV("liveDl",String.format(Locale.US,"%.2f Mbps",dl));if(ul>=0)setV("liveUl",String.format(Locale.US,"%.2f Mbps",ul));if(td>=0){setV("totalDl",bytes(td));prevDl=td;}if(tu>=0){setV("totalUl",bytes(tu));prevUl=tu;}if(!dur.isEmpty())setV("uptime",time(dur));prevTs=now;}
  long lng(String s){try{return Long.parseLong(s.trim());}catch(Exception e){return -1;}} String bytes(long b){if(b>=1073741824)return String.format(Locale.US,"%.2f GB",b/1073741824.0);if(b>=1048576)return String.format(Locale.US,"%.1f MB",b/1048576.0);return String.format(Locale.US,"%.0f KB",b/1024.0);} String time(String s){try{long n=Long.parseLong(s);return String.format(Locale.US,"%d:%02d:%02d",n/3600,(n%3600)/60,n%60);}catch(Exception e){return s;}}
  void bands(){if(!authenticated){loginDialog();return;}String[] n=new String[BANDS.length];for(int i=0;i<n.length;i++)n[i]=BANDS[i][0];new AlertDialog.Builder(this).setTitle("الترددات والدمج — تحكم مباشر").setItems(n,(d,w)->applyBand(BANDS[w][0],BANDS[w][1],BANDS[w][2])).setNegativeButton("إلغاء",null).show();}
  void applyBand(String label,String lte,String mode){String js="javascript:(async()=>{try{let s=await (await fetch('/api/webserver/SesTokInfo',{credentials:'same-origin'})).text();let t=(s.match(/<TokInfo>(.*?)<\\/TokInfo>/)||[])[1];if(!t)return 'NO_TOKEN';let body='<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?><request><NetworkMode>"+mode+"</NetworkMode><NetworkBand>3FFFFFFF</NetworkBand><LTEBand>"+lte+"</LTEBand></request>';let r=await fetch('/api/net/net-mode',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/xml','__RequestVerificationToken':t},body});return await r.text()}catch(e){return 'NETERR'}})()";web.evaluateJavascript(js,v->{String o=decode(v);if(o.contains("OK")){status.setText("تم تطبيق "+label);prefs.edit().putString("lastBand",label).apply();h.postDelayed(this::refreshAll,1800);}else Toast.makeText(this,"تعذر تطبيق التردد",Toast.LENGTH_LONG).show();});}
  void capabilities(){if(!authenticated){loginDialog();return;}String js="javascript:(async()=>{let eps=['/api/device/information','/api/device/signal','/api/monitoring/status','/api/monitoring/traffic-statistics','/api/net/net-mode','/api/net/current-plmn','/api/wlan/host-list','/api/wlan/basic-settings','/api/dialup/profiles','/api/sms/sms-count','/api/pin/status','/api/pin/simlock','/api/device/control'];let out=[];for(let e of eps){try{let r=await fetch(e,{credentials:'same-origin'});let t=await r.text();out.push(e+'='+((r.ok&&!t.includes('<error>'))?'OK':'LIMITED'))}catch(x){out.push(e+'=NO')}}return out.join('\\n')})()";web.evaluateJavascript(js,v->new AlertDialog.Builder(this).setTitle("API / Firmware Capability Matrix").setMessage(decode(v)).setPositiveButton("حسنًا",null).show());}
  void simCenter(){if(!authenticated){loginDialog();return;}String js="javascript:(async()=>{const g=async u=>{try{return await (await fetch(u,{credentials:'same-origin'})).text()}catch(e){return ''}};return (await g('/api/pin/status'))+'|||'+(await g('/api/pin/simlock'))+'|||'+(await g('/api/net/current-plmn'))+'|||'+(await g('/api/device/information'))})()";web.evaluateJavascript(js,v->{String o=decode(v);String[] p=o.split("\\|\\|\\|",-1);String st=tag(p[0],"SimState"),lock=tag(p[1],"SimLockEnable"),rem=tag(p[1],"SimLockRemainTimes","pSimLockRemainTimes"),op=tag(p[2],"FullName","ShortName","Numeric"),fw=tag(p[3],"SoftwareVersion"),imei=tag(p[3],"Imei","IMEI");String msg="الحالة: "+("0".equals(lock)?"مفتوح لأي شبكة":"1".equals(lock)?"مقفول على شبكة":"غير معروف")+"\nSIM: "+st+"\nالمشغل: "+op+"\nمحاولات Unlock: "+rem+"\nIMEI: "+imei+"\nFirmware: "+fw;new AlertDialog.Builder(this).setTitle("SIM Unlock Center").setMessage(msg).setPositiveButton("حسنًا",null).show();});}
  void loadHosts(){if(!authenticated)return;web.evaluateJavascript("javascript:fetch('/api/wlan/host-list',{credentials:'same-origin'}).then(r=>r.text())",v->{String o=decode(v);Matcher m=Pattern.compile("<Host>(.*?)</Host>",Pattern.DOTALL).matcher(o);StringBuilder s=new StringBuilder();int n=0;while(m.find()){n++;String z=m.group(1);s.append(n).append(") ").append(tag(z,"HostName","ActualName","IpAddress")).append("\nIP: ").append(tag(z,"IpAddress","IPAddress")).append("\nMAC: ").append(tag(z,"MacAddress","MACAddress")).append("\n\n");}setV("hosts",String.valueOf(n));new AlertDialog.Builder(this).setTitle("الأجهزة المتصلة ("+n+")").setMessage(s.length()==0?"لا توجد بيانات":s.toString()).setPositiveButton("حسنًا",null).show();});}
  void deviceControl(){new AlertDialog.Builder(this).setTitle("الأجهزة و QoS").setMessage("يعرض التطبيق العملاء ويستخدم Rate Limit فقط عندما يوفر الراوتر API متوافقًا. لن يرسل أوامر غير موثوقة قد تقطع الشبكة.").setPositiveButton("عرض الأجهزة",(d,w)->loadHosts()).setNegativeButton("حسنًا",null).show();}
  void apn(){showRouter();} void sms(){showRouter();}
  void restart(){post("/api/device/control","<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><Control>1</Control></request>");}
  void post(String path,String body){String b=body.replace("'","\\'");String js="javascript:(async()=>{try{let s=await (await fetch('/api/webserver/SesTokInfo',{credentials:'same-origin'})).text();let t=(s.match(/<TokInfo>(.*?)<\\/TokInfo>/)||[])[1];let r=await fetch('"+path+"',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/xml','__RequestVerificationToken':t},body:'"+b+"'});return await r.text()}catch(e){return 'NETERR'}})()";web.evaluateJavascript(js,v->Toast.makeText(this,decode(v),Toast.LENGTH_LONG).show());}
  void safeRestore(){String[] a={"استرجاع إعداد الشبكة الأصلي","إعادة تشغيل الراوتر","فتح Factory Reset الرسمي"};new AlertDialog.Builder(this).setTitle("الاسترجاع الآمن").setItems(a,(d,w)->{if(w==0)applyBand("الوضع الأصلي","20800800D5","00");else if(w==1)restart();else showRouter();}).setNegativeButton("إلغاء",null).show();}
  void speedTest(){status.setText("جارٍ اختبار السرعة...");new Thread(()->{try{List<Double> ps=new ArrayList<>();int fail=0;for(int i=0;i<5;i++){try{ps.add(latency());}catch(Exception e){fail++;}}double ping=avg(ps),jit=jitter(ps),dl=download(5000000),ul=upload(1000000),loss=fail*20.0;String ts=new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(new Date());String band=cache.getOrDefault("band","—");String rec=ts+" | "+fmt(dl)+"↓ "+fmt(ul)+"↑ | Ping "+fmt(ping)+" | "+band;String old=prefs.getString("history","");double score=dl*2+num(cache.getOrDefault("sinr","0"))*1.5-ping*.25;double oldScore=Double.longBitsToDouble(prefs.getLong("bestScore",Double.doubleToLongBits(-9999)));SharedPreferences.Editor ed=prefs.edit().putString("history",rec+"\n"+old);if(score>oldScore&&!"—".equals(band))ed.putLong("bestScore",Double.doubleToLongBits(score)).putString("bestBand",band);ed.apply();runOnUiThread(()->{setV("dl",fmt(dl)+" Mbps");setV("ul",fmt(ul)+" Mbps");setV("ping",fmt(ping)+" ms");setV("jitter",fmt(jit)+" ms");setV("loss",fmt(loss)+"%");setV("bestBand",prefs.getString("bestBand","—"));status.setText("السرعة: "+fmt(dl)+"↓ / "+fmt(ul)+"↑ Mbps");});}catch(Exception e){runOnUiThread(()->status.setText("فشل اختبار السرعة: "+e.getMessage()));}}).start();}
  double latency()throws Exception{long a=System.nanoTime();HttpURLConnection c=(HttpURLConnection)new URL("https://speed.cloudflare.com/__down?bytes=1&x="+System.nanoTime()).openConnection();c.setConnectTimeout(5000);c.setReadTimeout(5000);InputStream in=c.getInputStream();in.read();in.close();return (System.nanoTime()-a)/1e6;}
  double download(int bytes)throws Exception{long a=System.nanoTime();HttpURLConnection c=(HttpURLConnection)new URL("https://speed.cloudflare.com/__down?bytes="+bytes+"&x="+System.nanoTime()).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(20000);InputStream in=new BufferedInputStream(c.getInputStream());byte[] b=new byte[32768];long n=0;int z;while((z=in.read(b))>0)n+=z;in.close();return n*8.0/((System.nanoTime()-a)/1e9)/1e6;}
  double upload(int bytes)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL("https://speed.cloudflare.com/__up").openConnection();c.setDoOutput(true);c.setRequestMethod("POST");c.setConnectTimeout(8000);c.setReadTimeout(20000);c.setFixedLengthStreamingMode(bytes);c.setRequestProperty("Content-Type","application/octet-stream");long a=System.nanoTime();OutputStream o=c.getOutputStream();byte[] b=new byte[32768];int left=bytes;while(left>0){int n=Math.min(left,b.length);o.write(b,0,n);left-=n;}o.close();InputStream in=c.getInputStream();while(in.read(b)>0){}in.close();return bytes*8.0/((System.nanoTime()-a)/1e9)/1e6;}
  double avg(List<Double>a){double s=0;for(double x:a)s+=x;return a.isEmpty()?0:s/a.size();} double jitter(List<Double>a){if(a.size()<2)return 0;double s=0;for(int i=1;i<a.size();i++)s+=Math.abs(a.get(i)-a.get(i-1));return s/(a.size()-1);} String fmt(double x){return String.format(Locale.US,"%.1f",x);}
  void smartOptimize(){new AlertDialog.Builder(this).setTitle("Auto Optimizer").setMessage("يعتمد على الإشارة وسجل السرعة وأفضل Band محفوظ. اختبر أكثر من تردد ثم ثبّت الأفضل.").setPositiveButton("اختبار السرعة",(d,w)->speedTest()).setNeutralButton("الترددات",(d,w)->bands()).setNegativeButton("إلغاء",null).show();}
  void pinBest(){String b=prefs.getString("bestBand","");if(b.isEmpty()){Toast.makeText(this,"اختبر أكثر من تردد أولًا",Toast.LENGTH_LONG).show();return;}for(String[] x:BANDS)if(x[0].equalsIgnoreCase(b)||("B"+x[0]).equalsIgnoreCase(b)){applyBand("أفضل تردد "+b,x[1],x[2]);return;}new AlertDialog.Builder(this).setTitle("أفضل تردد").setMessage("أفضل نتيجة: "+b+". افتح مدير الترددات لتثبيته يدويًا.").setPositiveButton("الترددات",(d,w)->bands()).show();}
  void diagnose(){String s="SINR: "+cache.getOrDefault("sinr","—")+"\nRSRP: "+cache.getOrDefault("rsrp","—")+"\nRSRQ: "+cache.getOrDefault("rsrq","—")+"\nBand: "+cache.getOrDefault("band","—")+"\n\nالجودة الحالية: "+cache.getOrDefault("quality","—");new AlertDialog.Builder(this).setTitle("التشخيص الذكي").setMessage(s).setPositiveButton("حسنًا",null).show();}
  void history(){new AlertDialog.Builder(this).setTitle("سجل السرعة").setMessage(prefs.getString("history","لا توجد نتائج بعد")).setPositiveButton("حسنًا",null).show();}
  void showRouter(){scroll.setVisibility(View.GONE);nav.setVisibility(View.GONE);status.setVisibility(View.GONE);routerBar.setVisibility(View.VISIBLE);web.setVisibility(View.VISIBLE);web.setLayoutParams(new LinearLayout.LayoutParams(-1,0,1));web.loadUrl(baseUrl+"/");}
  void hideRouter(){web.setVisibility(View.GONE);web.setLayoutParams(new LinearLayout.LayoutParams(-1,0));routerBar.setVisibility(View.GONE);status.setVisibility(View.VISIBLE);scroll.setVisibility(View.VISIBLE);nav.setVisibility(View.VISIBLE);}
  void fitRouter(){web.setInitialScale(90);web.getSettings().setTextZoom(92);}
  void about(){new AlertDialog.Builder(this).setTitle("Shahboun Router v0.11.2").setMessage("Deep Huawei HiLink Driver + Universal Router Core\n\n• Live dashboard كل ثانيتين\n• Direct Band Manager\n• Differential live traffic\n• Speed history + Best Band\n• SIM Lock diagnostics\n• API/Firmware Explorer\n• Safe Restore\n• Generic design for other routers\n\nتصميم وتطوير: أحمد شهبون\n0921984045").setPositiveButton("حسنًا",null).show();}
  @Override public void onBackPressed(){if(web.getVisibility()==View.VISIBLE){hideRouter();return;}super.onBackPressed();}
  class JsBridge{
    @JavascriptInterface public void data(String k,String x){runOnUiThread(()->{if("signal".equals(k))parseSignal(x);else if("status".equals(k))parseStatus(x);else if("device".equals(k))parseDevice(x);else if("net".equals(k))parseNet(x);else if("traffic".equals(k))parseTraffic(x);else if("hosts".equals(k)&&!err(x))setV("hosts",String.valueOf(count(x,"<Host>")));else if("plmn".equals(k)&&!err(x))setV("operator",tag(x,"FullName","ShortName","Numeric"));});}
  }
  int count(String s,String q){int n=0,p=0;while((p=s.indexOf(q,p))>=0){n++;p+=q.length();}return n;}
}
