package com.shahboun.e5785;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.regex.*;

public class MainActivity extends Activity {
    final Handler h = new Handler(Looper.getMainLooper());
    final String BASE = "http://192.168.8.1";
    final int BG=Color.rgb(5,10,16), CARD=Color.rgb(13,27,39), CARD2=Color.rgb(19,41,56), TEXT=Color.rgb(245,249,252), MUTED=Color.rgb(174,196,211), ACC=Color.rgb(54,196,216), RED=Color.rgb(235,91,91), GREEN=Color.rgb(76,207,139);
    final Map<String,TextView> fields=new LinkedHashMap<>();
    final Map<String,String> values=new HashMap<>();
    final Map<String,Boolean> caps=new LinkedHashMap<>();
    SharedPreferences prefs;
    LinearLayout root, body; TextView status; WebView web;
    boolean logged=false, live=false, loginBusy=false;
    long prevDl=-1,prevUl=-1,prevTs=0;
    String password="admin";

    @Override public void onCreate(Bundle b){
        super.onCreate(b);
        prefs=getSharedPreferences("e5785",MODE_PRIVATE); password=prefs.getString("password","admin");
        getWindow().setStatusBarColor(BG); getWindow().setNavigationBarColor(BG);
        build(); web.loadUrl(BASE+"/"); h.postDelayed(this::loginDialog,800);
    }
    int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}    
    GradientDrawable shape(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(40,67,82));return g;}
    TextView text(String s,int z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(dp(10),dp(9),dp(10),dp(9));return t;}
    TextView btn(String s,View.OnClickListener l){TextView b=text(s,13,TEXT);b.setGravity(Gravity.CENTER);b.setBackground(shape(CARD2,16));b.setOnClickListener(l);return b;}
    void build(){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(16),dp(12),dp(12),dp(8));
        LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);
        TextView title=text("Shahboun Router",24,TEXT);title.setPadding(0,0,0,0);names.addView(title);
        TextView sub=text("Huawei E5785Lh-22c Edition  •  v1.0.0",11,MUTED);sub.setPadding(0,2,0,0);names.addView(sub);head.addView(names,new LinearLayout.LayoutParams(0,-2,1));
        head.addView(btn("تحديث",v->refreshAll()),new LinearLayout.LayoutParams(dp(90),dp(44)));root.addView(head);
        status=text("جارٍ الاتصال بـ E5785Lh-22c…",12,TEXT);status.setGravity(Gravity.CENTER);status.setBackgroundColor(Color.rgb(8,19,28));root.addView(status,new LinearLayout.LayoutParams(-1,dp(44)));
        ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(8),dp(14),dp(22));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        web=new WebView(this);WebSettings ws=web.getSettings();ws.setJavaScriptEnabled(true);ws.setDomStorageEnabled(true);ws.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);ws.setCacheMode(WebSettings.LOAD_NO_CACHE);web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient());web.setVisibility(View.GONE);root.addView(web,new LinearLayout.LayoutParams(1,1));
        LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(7,17,25));String[] ns={"الرئيسية","الترددات","الأجهزة","الأدوات"};for(int i=0;i<ns.length;i++){final int p=i;TextView x=text(ns[i],11,MUTED);x.setGravity(Gravity.CENTER);x.setOnClickListener(v->page(p));nav.addView(x,new LinearLayout.LayoutParams(0,dp(60),1));}root.addView(nav);setContentView(root);page(0);
    }
    void clear(){body.removeAllViews();fields.clear();}
    void section(String a,String b){TextView x=text(a,19,TEXT);x.setPadding(2,dp(14),2,0);body.addView(x);TextView y=text(b,11,MUTED);y.setPadding(2,0,2,dp(7));body.addView(y);}
    void card(String[][] rows){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(8),dp(12),dp(8));c.setBackground(shape(CARD,19));for(String[] r:rows){LinearLayout q=new LinearLayout(this);q.setGravity(Gravity.CENTER_VERTICAL);TextView l=text(r[0],12,MUTED);TextView v=text(values.getOrDefault(r[1],"—"),12,TEXT);v.setGravity(Gravity.END);fields.put(r[1],v);q.addView(l,new LinearLayout.LayoutParams(0,-2,1));q.addView(v,new LinearLayout.LayoutParams(0,-2,1.2f));c.addView(q);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));body.addView(c,p);}
    void grid(String[] labels,View.OnClickListener[] actions){for(int i=0;i<labels.length;i+=2){LinearLayout r=new LinearLayout(this);r.setPadding(0,dp(4),0,dp(4));r.addView(btn(labels[i],actions[i]),new LinearLayout.LayoutParams(0,dp(58),1));Space s=new Space(this);r.addView(s,new LinearLayout.LayoutParams(dp(8),1));if(i+1<labels.length)r.addView(btn(labels[i+1],actions[i+1]),new LinearLayout.LayoutParams(0,dp(58),1));body.addView(r);}}
    void set(String k,String v){if(v==null||v.trim().isEmpty())return;values.put(k,v.trim());TextView t=fields.get(k);if(t!=null)t.setText(v.trim());}
    void page(int p){live=false;clear();if(p==0)home();else if(p==1)bandsPage();else if(p==2)devicesPage();else toolsPage();}
    void home(){
        section("الحالة المباشرة","قراءات HiLink تتحدث كل ثانيتين بعد الدخول");
        card(new String[][]{{"الموديل","model"},{"Firmware","firmware"},{"المشغل","operator"},{"نوع الشبكة","network"},{"Band","band"},{"RSRP","rsrp"},{"RSRQ","rsrq"},{"SINR","sinr"},{"RSSI","rssi"},{"Cell ID","cell"},{"PCI","pci"},{"EARFCN","earfcn"},{"البطارية","battery"}});
        section("الترافيك","سرعة لحظية محسوبة من عدادات الراوتر");card(new String[][]{{"تنزيل لحظي","liveDl"},{"رفع لحظي","liveUl"},{"إجمالي تنزيل","totalDl"},{"إجمالي رفع","totalUl"},{"مدة الاتصال","uptime"},{"أجهزة Wi‑Fi","hosts"},{"آخر Speed Test","speed"},{"Ping","ping"}});
        grid(new String[]{"فحص القدرات","أفضل تردد","اختبار سرعة","إعادة اتصال","إعادة تشغيل","SIM / PIN","SMS","Wi‑Fi / APN"},new View.OnClickListener[]{v->probe(),v->showBest(),v->speedTest(),v->reconnect(),v->reboot(),v->simInfo(),v->smsDialog(),v->wifiApn()});
        live=true;tick(); if(logged)refreshAll();
    }
    void bandsPage(){section("Band Manager","يقرأ الوضع الحالي ويحفظه قبل أي تعديل");card(new String[][]{{"NetworkMode","netMode"},{"NetworkBand","netBand"},{"LTEBand","lteBand"},{"أفضل إعداد محفوظ","bestBand"}});String[] names={"تلقائي / الأصل","B1","B3","B7","B8","B20","B3+B7","B3+B20","B7+B20","B3+B7+B20"};String[] masks={"20800800D5","1","4","40","80","80000","44","80004","80040","80044"};View.OnClickListener[] aa=new View.OnClickListener[names.length];for(int i=0;i<names.length;i++){final int j=i;aa[i]=v->applyBand(names[j],masks[j],j==0?"00":"03");}grid(names,aa);grid(new String[]{"حفظ الحالي Snapshot","استرجاع Snapshot","Benchmark تلقائي","تحديث القراءة"},new View.OnClickListener[]{v->snapshot(),v->restoreBand(),v->benchmark(),v->refreshAll()});if(logged)refreshAll();}
    void devicesPage(){section("الأجهزة و Wi‑Fi","قراءة الأجهزة المتصلة وإعدادات الشبكة");card(new String[][]{{"SSID","ssid"},{"عدد الأجهزة","hosts"},{"Wi‑Fi Users","wifiUsers"},{"عنوان الراوتر","gateway"}});grid(new String[]{"قائمة الأجهزة","تحديث","إعداد Wi‑Fi","حظر/سماح"},new View.OnClickListener[]{v->hostsDialog(),v->refreshAll(),v->wifiApn(),v->hostsDialog()});if(logged)refreshAll();}
    void toolsPage(){section("أدوات E5785","تشخيص، رسائل، SIM واختبارات");card(new String[][]{{"آخر Speed Test","speed"},{"Ping","ping"},{"أفضل Band","bestBand"},{"SIM","sim"},{"Network Lock","simlock"},{"SMS","sms"}});grid(new String[]{"اختبار سرعة","فحص القدرات","SIM / PIN","SMS","إعادة اتصال","إعادة تشغيل","واجهة الراوتر","حول التطبيق"},new View.OnClickListener[]{v->speedTest(),v->probe(),v->simInfo(),v->smsDialog(),v->reconnect(),v->reboot(),v->showWeb(),v->about()});}
    void tick(){if(!live)return;if(logged)refreshAll();h.postDelayed(this::tick,2000);}

    void loginDialog(){if(loginBusy||isFinishing())return;loginBusy=true;LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(20),0,dp(20),0);EditText u=new EditText(this);u.setText("admin");u.setEnabled(false);b.addView(u);EditText p=new EditText(this);p.setText(password);p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);b.addView(p);AlertDialog d=new AlertDialog.Builder(this).setTitle("دخول E5785Lh-22c").setMessage("اسم المستخدم admin — سيتم استخدام جلسة واجهة Huawei الأصلية.").setView(b).setPositiveButton("اتصال",null).create();d.setCancelable(false);d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{password=p.getText().toString();if(password.isEmpty())password="admin";prefs.edit().putString("password",password).apply();status.setText("جارٍ تسجيل الدخول…");web.loadUrl(BASE+"/");h.postDelayed(()->webLogin(d),900);}));d.show();}
    void webLogin(AlertDialog d){String p=esc(password);String js="javascript:(()=>{try{let u=document.querySelector('input[name=username],#username,input[type=text]');let pw=document.querySelector('input[name=password],#password,input[type=password]');if(!pw)return 'NOFORM';if(u)u.value='admin';pw.value='"+p+"';pw.dispatchEvent(new Event('input',{bubbles:true}));pw.dispatchEvent(new Event('change',{bubbles:true}));let b=document.querySelector('#login_btn,#loginbutton,#loginBtn,button[type=submit],input[type=submit],.login_button,.btn_login,[onclick*=login i]');if(b){b.click();return 'CLICK'}if(pw.form){pw.form.submit();return 'SUBMIT'}return 'NOBUTTON'}catch(e){return 'ERR'}})()";web.evaluateJavascript(js,r->h.postDelayed(()->verifyLogin(d),2200));}
    void verifyLogin(AlertDialog d){apiGet("/api/device/information",x->{loginBusy=false;String m=tag(x,"DeviceName");if(m.isEmpty())m=tag(x,"Classify");if(x.contains("<error>")||x.isEmpty()){status.setText("فشل الدخول — تحقق من الرمز");Toast.makeText(this,"لم تقبل جلسة الراوتر. تأكد من رمز admin.",Toast.LENGTH_LONG).show();return;}logged=true;if(d.isShowing())d.dismiss();set("model",m.isEmpty()?"E5785Lh-22c":m);status.setText("متصل • Huawei E5785Lh-22c / HiLink");probe();refreshAll();});}
    String esc(String s){return s.replace("\\","\\\\").replace("'","\\'").replace("\n","");}
    String decode(String s){if(s==null||s.equals("null"))return "";if(s.startsWith("\"")&&s.endsWith("\""))s=s.substring(1,s.length()-1);return s.replace("\\u003C","<").replace("\\u003E",">").replace("\\\"","\"").replace("\\n","\n").replace("\\/","/").replace("\\\\","\\");}
    interface CB{void ok(String x);}    
    void apiGet(String path,CB cb){String js="javascript:(async()=>{try{return await (await fetch('"+path+"',{credentials:'same-origin',cache:'no-store'})).text()}catch(e){return '<error>'+e+'</error>'}})()";web.evaluateJavascript(js,v->cb.ok(decode(v)));}
    void apiPost(String path,String xml,CB cb){String e=esc(xml);String js="javascript:(async()=>{try{let s=await (await fetch('/api/webserver/SesTokInfo',{credentials:'same-origin',cache:'no-store'})).text();let m=s.match(/<TokInfo>(.*?)<\\/TokInfo>/i);if(!m)return '<error>NO_TOKEN</error>';let r=await fetch('"+path+"',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/xml','__RequestVerificationToken':m[1]},body:'"+e+"'});return await r.text()}catch(e){return '<error>'+e+'</error>'}})()";web.evaluateJavascript(js,v->cb.ok(decode(v)));}
    String tag(String x,String n){if(x==null)return "";Matcher m=Pattern.compile("<"+Pattern.quote(n)+">(.*?)</"+Pattern.quote(n)+">",Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(x);return m.find()?m.group(1).trim():"";}
    long num(String x,String n){try{return Long.parseLong(tag(x,n));}catch(Exception e){return -1;}}

    void refreshAll(){if(!logged)return;apiGet("/api/device/information",x->{set("model",pick(tag(x,"DeviceName"),"E5785Lh-22c"));set("firmware",pick(tag(x,"SoftwareVersion"),tag(x,"SoftwareVersion2")));});apiGet("/api/device/signal",this::parseSignal);apiGet("/api/monitoring/status",this::parseStatus);apiGet("/api/monitoring/traffic-statistics",this::parseTraffic);apiGet("/api/net/current-plmn",x->set("operator",pick(tag(x,"FullName"),tag(x,"ShortName"))));apiGet("/api/net/net-mode",x->{set("netMode",tag(x,"NetworkMode"));set("netBand",tag(x,"NetworkBand"));set("lteBand",tag(x,"LTEBand"));});apiGet("/api/wlan/basic-settings",x->{set("ssid",pick(tag(x,"WifiSsid"),tag(x,"SSID")));set("wifiUsers",pick(tag(x,"WifiMaxUsers"),tag(x,"MaxAssoc")));});apiGet("/api/wlan/host-list",x->{int c=count(x,"<Host>");set("hosts",String.valueOf(c));});}
    int count(String s,String q){int c=0,p=0;while(s!=null&&(p=s.indexOf(q,p))>=0){c++;p+=q.length();}return c;}
    String pick(String a,String b){return a==null||a.isEmpty()?b:a;}
    void parseSignal(String x){set("rsrp",tag(x,"rsrp"));set("rsrq",tag(x,"rsrq"));set("sinr",pick(tag(x,"sinr"),tag(x,"Sinr")));set("rssi",tag(x,"rssi"));set("cell",pick(tag(x,"cell_id"),tag(x,"CellId")));set("pci",pick(tag(x,"pci"),tag(x,"Pci")));set("earfcn",pick(tag(x,"earfcn"),tag(x,"Earfcn")));set("band",pick(tag(x,"band"),tag(x,"Band")));}
    void parseStatus(String x){set("battery",pick(tag(x,"BatteryPercent"),tag(x,"BatteryLevel")));String n=tag(x,"CurrentNetworkTypeEx");if(n.isEmpty())n=tag(x,"CurrentNetworkType");set("network",n);}
    void parseTraffic(String x){long dl=num(x,"CurrentDownload"),ul=num(x,"CurrentUpload"),td=num(x,"TotalDownload"),tu=num(x,"TotalUpload"),dur=num(x,"CurrentConnectTime");if(td>=0)set("totalDl",fmtBytes(td));if(tu>=0)set("totalUl",fmtBytes(tu));if(dur>=0)set("uptime",fmtTime(dur));long now=System.currentTimeMillis();if(prevTs>0){double sec=(now-prevTs)/1000.0;if(dl>=0&&prevDl>=0)set("liveDl",fmtRate(Math.max(0,dl-prevDl)/sec));if(ul>=0&&prevUl>=0)set("liveUl",fmtRate(Math.max(0,ul-prevUl)/sec));}prevDl=dl;prevUl=ul;prevTs=now;}
    String fmtBytes(long b){double v=b;String[] u={"B","KB","MB","GB","TB"};int i=0;while(v>=1024&&i<u.length-1){v/=1024;i++;}return String.format(Locale.US,"%.2f %s",v,u[i]);}
    String fmtRate(double bps){return String.format(Locale.US,"%.2f Mbps",bps*8/1000000.0);}
    String fmtTime(long s){return String.format(Locale.US,"%02d:%02d:%02d",s/3600,(s%3600)/60,s%60);}

    void probe(){if(!logged)return;String[] paths={"/api/device/information","/api/device/signal","/api/monitoring/status","/api/monitoring/traffic-statistics","/api/net/current-plmn","/api/net/net-mode","/api/pin/status","/api/pin/simlock","/api/sms/sms-count","/api/wlan/host-list","/api/wlan/basic-settings","/api/dialup/connection"};caps.clear();final int[] left={paths.length};for(String p:paths)apiGet(p,x->{caps.put(p,!x.isEmpty()&&!x.contains("<error>"));if(--left[0]==0){status.setText("فحص القدرات اكتمل • "+supported()+" / "+paths.length+" متاحة");}});}
    int supported(){int n=0;for(Boolean b:caps.values())if(Boolean.TRUE.equals(b))n++;return n;}
    void showCaps(){StringBuilder s=new StringBuilder();for(Map.Entry<String,Boolean>e:caps.entrySet())s.append(e.getValue()?"✓ ":"✕ ").append(e.getKey()).append("\n");new AlertDialog.Builder(this).setTitle("قدرات Firmware").setMessage(s.length()==0?"شغّل فحص القدرات أولًا":s.toString()).setPositiveButton("حسنًا",null).show();}
    void snapshot(){apiGet("/api/net/net-mode",x->{String m=tag(x,"NetworkMode"),b=tag(x,"NetworkBand"),l=tag(x,"LTEBand");prefs.edit().putString("snapMode",m).putString("snapBand",b).putString("snapLte",l).apply();Toast.makeText(this,"تم حفظ إعداد الشبكة الحالي",Toast.LENGTH_SHORT).show();});}
    void applyBand(String name,String mask,String mode){snapshot();String xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><NetworkMode>"+mode+"</NetworkMode><NetworkBand>3FFFFFFF</NetworkBand><LTEBand>"+mask+"</LTEBand></request>";apiPost("/api/net/net-mode",xml,x->{if(x.contains("OK")){prefs.edit().putString("lastBand",name).apply();set("bestBand",name);Toast.makeText(this,"تم تطبيق "+name,Toast.LENGTH_LONG).show();h.postDelayed(this::refreshAll,3000);}else Toast.makeText(this,"الراوتر رفض الأمر: "+tag(x,"code"),Toast.LENGTH_LONG).show();});}
    void restoreBand(){String m=prefs.getString("snapMode","00"),b=prefs.getString("snapBand","3FFFFFFF"),l=prefs.getString("snapLte","20800800D5");String xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><NetworkMode>"+m+"</NetworkMode><NetworkBand>"+b+"</NetworkBand><LTEBand>"+l+"</LTEBand></request>";apiPost("/api/net/net-mode",xml,x->Toast.makeText(this,x.contains("OK")?"تم استرجاع Snapshot":"تعذر الاسترجاع",Toast.LENGTH_LONG).show());}
    void reconnect(){String xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><Action>1</Action></request>";apiPost("/api/dialup/mobile-dataswitch",xml,x->{if(!x.contains("OK")){apiPost("/api/dialup/connection","<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><RoamAutoConnectEnable>1</RoamAutoConnectEnable><MaxIdelTime>0</MaxIdelTime><ConnectMode>0</ConnectMode><MTU>1500</MTU><auto_dial_switch>1</auto_dial_switch></request>",y->{});}Toast.makeText(this,"تم إرسال أمر إعادة الاتصال",Toast.LENGTH_SHORT).show();});}
    void reboot(){new AlertDialog.Builder(this).setTitle("إعادة تشغيل الراوتر").setMessage("سيقطع الاتصال لثوانٍ ثم يعود.").setPositiveButton("إعادة تشغيل",(d,w)->apiPost("/api/device/control","<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><Control>1</Control></request>",x->Toast.makeText(this,"تم إرسال الأمر",Toast.LENGTH_SHORT).show())).setNegativeButton("إلغاء",null).show();}
    void simInfo(){apiGet("/api/pin/status",a->apiGet("/api/pin/simlock",b->{set("sim",pick(tag(a,"SimState"),tag(a,"SimStatus")));set("simlock",pick(tag(b,"SimLockStatus"),tag(b,"SimlockStatus")));new AlertDialog.Builder(this).setTitle("SIM / PIN").setMessage("SIM: "+values.getOrDefault("sim","—")+"\nPIN retries: "+pick(tag(a,"PinRemainingTimes"),"—")+"\nPUK retries: "+pick(tag(a,"PukRemainingTimes"),"—")+"\nNetwork Lock: "+values.getOrDefault("simlock","—")).setPositiveButton("حسنًا",null).show();}));}
    void smsDialog(){apiGet("/api/sms/sms-count",x->{set("sms",pick(tag(x,"LocalInbox"),tag(x,"LocalUnread")));LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);EditText num=new EditText(this);num.setHint("رقم الهاتف");b.addView(num);EditText msg=new EditText(this);msg.setHint("الرسالة");b.addView(msg);new AlertDialog.Builder(this).setTitle("SMS • الوارد: "+values.getOrDefault("sms","—")).setView(b).setPositiveButton("إرسال",(d,w)->sendSms(num.getText().toString(),msg.getText().toString())).setNegativeButton("إلغاء",null).show();});}
    void sendSms(String n,String m){if(n.trim().isEmpty()||m.trim().isEmpty())return;String xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><Index>-1</Index><Phones><Phone>"+xml(n)+"</Phone></Phones><Sca></Sca><Content>"+xml(m)+"</Content><Length>"+m.length()+"</Length><Reserved>1</Reserved><Date>-1</Date></request>";apiPost("/api/sms/send-sms",xml,x->Toast.makeText(this,x.contains("OK")?"تم إرسال الرسالة":"تعذر الإرسال",Toast.LENGTH_LONG).show());}
    String xml(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
    void hostsDialog(){apiGet("/api/wlan/host-list",x->{StringBuilder s=new StringBuilder();Matcher m=Pattern.compile("<Host>(.*?)</Host>",Pattern.DOTALL).matcher(x);int i=1;while(m.find()){String z=m.group(1);s.append(i++).append(". ").append(pick(tag(z,"HostName"),"جهاز")).append("\nIP: ").append(tag(z,"IpAddress")).append("\nMAC: ").append(tag(z,"MacAddress")).append("\n\n");}new AlertDialog.Builder(this).setTitle("الأجهزة المتصلة").setMessage(s.length()==0?"لا توجد بيانات":s.toString()).setPositiveButton("حسنًا",null).show();});}
    void wifiApn(){apiGet("/api/wlan/basic-settings",w->apiGet("/api/dialup/profiles",a->{String s="SSID: "+pick(tag(w,"WifiSsid"),tag(w,"SSID"))+"\nMax users: "+pick(tag(w,"WifiMaxUsers"),tag(w,"MaxAssoc"))+"\nAPN: "+pick(tag(a,"ApnName"),tag(a,"Apn"))+"\n\nالخيارات تُعرض فقط حسب ما يسمح به Firmware جهازك.";new AlertDialog.Builder(this).setTitle("Wi‑Fi / APN").setMessage(s).setPositiveButton("حسنًا",null).show();}));}
    void showWeb(){web.setVisibility(View.VISIBLE);web.getLayoutParams().width=-1;web.getLayoutParams().height=dp(500);web.requestLayout();web.loadUrl(BASE+"/");new AlertDialog.Builder(this).setTitle("واجهة Huawei").setMessage("تم فتح واجهة الراوتر أسفل الصفحة. ارجع للرئيسية لإخفائها.").setPositiveButton("حسنًا",null).show();}
    void speedTest(){status.setText("جارٍ اختبار السرعة…");new Thread(()->{double mbps=0;long ping=-1;try{long p0=System.nanoTime();InetAddress.getByName("1.1.1.1").isReachable(1500);ping=(System.nanoTime()-p0)/1000000;URL u=new URL("https://speed.cloudflare.com/__down?bytes=5000000");URLConnection c=u.openConnection();c.setConnectTimeout(5000);c.setReadTimeout(10000);InputStream in=c.getInputStream();byte[] b=new byte[32768];long n=0,t=System.nanoTime();int r;while((r=in.read(b))>0)n+=r;in.close();double sec=(System.nanoTime()-t)/1e9;mbps=n*8/sec/1e6;}catch(Exception ignored){}final double f=mbps;final long pg=ping;runOnUiThread(()->{set("speed",String.format(Locale.US,"%.2f Mbps",f));set("ping",pg+" ms");prefs.edit().putFloat("lastSpeed",(float)f).apply();status.setText("اكتمل اختبار السرعة");});}).start();}
    void benchmark(){new AlertDialog.Builder(this).setTitle("Benchmark الترددات").setMessage("الاختبار الآلي الكامل سيغيّر التردد عدة مرات وقد يقطع الشبكة مؤقتًا. في هذه النسخة التجريبية استخدم الترددات يدويًا واعمل Speed Test؛ التطبيق يحفظ آخر أفضل نتيجة بدون المخاطرة بفقد الاتصال.").setPositiveButton("حسنًا",null).show();}
    void showBest(){String b=prefs.getString("lastBand","لم يتم تحديده بعد");float s=prefs.getFloat("lastSpeed",0);new AlertDialog.Builder(this).setTitle("أفضل نتيجة محفوظة").setMessage("Band: "+b+"\nآخر سرعة: "+String.format(Locale.US,"%.2f Mbps",s)).setPositiveButton("حسنًا",null).show();}
    void about(){new AlertDialog.Builder(this).setTitle("Shahboun Router E5785 v1.0.0").setMessage("تطبيق جديد من الصفر ومخصص لـ Huawei E5785Lh-22c / HiLink.\n\n• Live Dashboard\n• Band / Multi-Band\n• Snapshot / Restore\n• Speed Test\n• Capability Scan\n• Traffic / Battery\n• SMS\n• SIM / PIN\n• Wi‑Fi / APN\n• Hosts\n• Reconnect / Reboot\n\nتصميم وتطوير: أحمد شهبون\n0921984045").setPositiveButton("حسنًا",null).show();}
    @Override public void onBackPressed(){if(web.getVisibility()==View.VISIBLE){web.setVisibility(View.GONE);web.getLayoutParams().height=1;web.requestLayout();return;}super.onBackPressed();}
}
